apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN5ekNDQWJPZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRFNU1URXhNekE1TkRZME9Gb1hEVEk1TVRFeE1EQTVOVEUwT0Zvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTFVSCllwbUNtVTBFdmhnajlJL2VzaUVGT0VGZTBRZTZob3NFVlp1RkF2Y1ZPdmhTMHJZcDdlMEw5WGovYzNycDNHNU8KaFh1N2F2RFA4ZTF6OSt3MGl5VGxjdlFBczNmR2x0RWorZEk2SFJGdXlnT0hVSmlFWXpHK1M2UCsxVVh6NzZiZQpkSWkwSzBXbzlLWVRBZHJuNmZaQWJiRGVNOGRLRU5MOGNlUHZaeDJ4OTcrSmJvRGtsM1ArQW52dDB4OGFwQ0h2CmlpcGZZaVowY1ZDZmpGVzN2OVh3L1hGWmtZb29HRWZtYUw2c2Z4dTJKOTh4M1ArNndMaGJGUmdoK0hIcFJWL1MKYkREZk9MRDAycVJ0SjFhdUZBek9leHlQWXVXYlQ3MjdubndkN1NyOHZLMm4zWVcwYTA0aWswanlwOUdOY1MyNwpHcS9YWU5NNHJwSy8wR21veGRzQ0F3RUFBYU1tTUNRd0RnWURWUjBQQVFIL0JBUURBZ0trTUJJR0ExVWRFd0VCCi93UUlNQVlCQWY4Q0FRQXdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBRW53cVVpd0tFT0lURzc1WFRabklDUm4KcDJ3VDMvZE1LRVk4Um0vZXpBYldTRDFEdllBb2RPTVlwelFoMG93eTd2QUhqajI1bm1XMlBXT3pRNldjakpYbgpGTS9SN2tCK0FJL3pOVWJCcEV1YlJ5eXY4ckl6SjBuRHdpQmtrRTlvckNBNDJQaHJVamdjd2NIek1QaEpLSDlOCkhpemxZd25GVzlOUFVWSWszSFJPV2xOTXpic1F1eHM1QnczUjdhSFdXbE5IdHBIc0JEUG1NdVFSVXlRMnV4UnYKOWdDbWpIb25XZmQ0L2h3Ym5NMnNUbWo2eGFBSExSOXVsaThHcnVyQVUwZGt3YTByb09OSFU2clFia01SdVN2Mgp5Y050VlZPU2ZyOER1WGN2M0puQmc5eTBoMDUwdmp2ZlJkZ2plaCtBVm12aGx3eWRJODYwUjl3Z0h5VEhXWHc9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://k8s-cluster-vforum-apiserver-1268125924.us-east-1.elb.amazonaws.com:6443
  name: k8s-cluster-vforum
contexts:
- context:
    cluster: k8s-cluster-vforum
    user: k8s-cluster-vforum
  name: oidc-k8s-cluster-vforum
current-context: oidc-k8s-cluster-vforum
kind: Config
preferences: {}
users:
- name: k8s-cluster-vforum
  user:
    exec:
      apiVersion: "client.authentication.k8s.io/v1beta1"
      command: tmc
      args: ["cluster", "generate-token"]
      env:
      - name: ISSUER
        value: https://console.cloud.vmware.com/csp/gateway/am/api
      - name: ORG_ID
        value: fa2c1d78-9f00-4e30-8268-4ab81862080d
      - name: CLIENT_ID
        value: vmware-oidc-e07d8715-05fa-11ea-88e5-be6f6414c996
      - name: CLIENT_SECRET
        value: 5IJyQK1DB58GEPcaPbYqkIpGZi3Oab85FqlECpjKW3AJS27mpp
